# Generated by Django 3.2.13 on 2022-05-04 00:36

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('breed', models.CharField(choices=[('Akita', 'Akita'), ('American Foxhound', 'American Foxhound'), ('Australian Cattle Dog', 'Australian Cattle Dog'), ('Basset Hound', 'Basset Hound'), ('Beagle', 'Beagle'), ('Border Collie', 'Border Collie'), ('Boxer', 'Boxer'), ('Bulldog', 'Bulldog'), ('Chihuahua', 'Chihuahua'), ('Chow Chow', 'Chow Chow')], max_length=100, verbose_name='Breed')),
                ('image', stdimage.models.StdImageField(upload_to='dogs', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Dog',
                'verbose_name_plural': 'Dogs',
            },
        ),
    ]
